[vlive]
title = "SMTOWN ─ Media Board"
url = "https://vlive.tv/channel/FD53B/board/3530?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
contentSelector = ".upload_time--wtBj9"
waitUntil = "networkidle"

[vlive_notice]
title = "SMTOWN ─ Notice"
url = "https://www.vlive.tv/channel/FD53B/board/69"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = ".writer--pwvK2"
waitUntil = "networkidle"
