[vlive]
title = "SMTOWN ─ Media Board"
url = "https://vlive.tv/channel/FD53B/board/3530?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[data-click]"
imageSelector = "span[class^='covered_image']"
contentSelector = ".upload_time--wtBj9"
waitUntil = "networkidle"

[vlive_notice]
title = "SMTOWN ─ Notice"
url = "https://www.vlive.tv/channel/FD53B/board/69"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = ".writer--pwvK2"
waitUntil = "networkidle"

[smtown_news]
title = "SMTOWN ─ News"
url = "https://www.smtown.com/news"
entrySelector = "ul.list_main.new_list li"
titleSelector = "span.title"
linkSelector = "a[class='btn_text']"
imageSelector = "a.btn_img.bg_cover"
contentSelector = "span.text_box"
waitUntil = "networkidle"

[smtown_notice]
title = "SMTOWN ─ Notice"
url = "https://www.smtown.com/notice"
entrySelector = "ul.list_main.new_list li"
titleSelector = "span.title"
linkSelector = "a.btn_text"
imageSelector = "a.btn_img.bg_cover"
contentSelector = "span.text_box"
waitUntil = "networkidle"

[smtown_musicians_top]
title = "SMTOWN ─ Musicians News"
url = "https://www.smtown.com/artist/news/1"
entrySelector = "div.column_box"
titleSelector = "span.title"
linkSelector = "a.btn_top.bg_cover"
imageSelector = "a.btn_top.bg_cover"
contentSelector = "span.text"
waitUntil = "networkidle"

[smtown_musicians]
title = "SMTOWN ─ Musicians News"
url = "https://www.smtown.com/artist/news/1"
entrySelector = "ul.list_main li"
titleSelector = "span.title"
linkSelector = "a.btn_text"
imageSelector = "a.btn_img.bg_cover"
contentSelector = "span.text"
waitUntil = "networkidle"

[smtown_actors_top]
title = "SMTOWN ─ Actors News"
url = "https://www.smtown.com/artist/news/2"
entrySelector = "div.column_box"
titleSelector = "span.title"
linkSelector = "a.btn_text"
imageSelector = "a.btn_top.bg_cover"
contentSelector = "span.text"
waitUntil = "networkidle"

[smtown_actors]
title = "SMTOWN ─ Actors News"
url = "https://www.smtown.com/artist/news/2"
entrySelector = "ul.list_main li"
titleSelector = "span.title"
linkSelector = "a.btn_text"
imageSelector = "a.btn_img.bg_cover"
contentSelector = "span.text"
waitUntil = "networkidle"

[naverpost_smtown_special]
title = "SMTOWN 신곡 포스트 ─ SPECIAL"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=434190&memberNo=41350603"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_smtown_upcoming]
title = "SMTOWN 신곡 포스트 ─ UPCOMING"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=434189&memberNo=41350603"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_smtown_station]
title = "SMTOWN 신곡 포스트 ─ SM STATION"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=434191&memberNo=41350603"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_smtown_playlist]
title = "SMTOWN 신곡 포스트 ─ PLAYLIST"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=434148&memberNo=41350603"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
